language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 19.3
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.6
sudo: false
after_script:
  - MIX_ENV=docs mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis
